{
 "title": "Energy Dashboard",
 "time": { "from": "2016-12-31T12:00:00.000Z", "to": "2025-01-01T12:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "energy",
    "query": "SELECT DISTINCT type_name AS __text, energy_type_id AS __value FROM Energy_Type_Dim"
   },
   {
    "name": "country",
    "query": "SELECT DISTINCT country_name AS __text, country_id AS __value FROM Country_Dim"
   },
   {
    "name": "year",
    "query": "SELECT DISTINCT year AS __text, year AS __value\nFROM Time_Dim\nORDER BY year"
   }
  ]
 },
 "panels": [
  {
   "title": "Evolution of energy production: ${country}, ${energy}, year ${year}",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    DATE_TRUNC('month', TO_DATE(CONCAT(t.year, '-', t.month, '-01'), 'YYYY-MM-DD')) AS \"time\",\n    SUM(e.energy_production) AS \"Production in TWh\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\nWHERE\n    e.country_id = $country\n    AND e.energy_type_id = $energy\n    AND t.year = $year\nGROUP BY\n    \"time\"\nORDER BY\n    \"time\""
    }
   ]
  },
  {
   "title": "Evolution of the public opinion: ${country}, ${energy}, year ${year}",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    DATE_TRUNC('month', TO_DATE(CONCAT(t.year, '-', t.month, '-01'), 'YYYY-MM-DD')) AS \"time\",\n    SUM(e.positive_opinion) AS \"Positive sentiments\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\nWHERE\n    e.country_id = $country\n    AND e.energy_type_id = $energy\n    AND t.year = $year\nGROUP BY\n    \"time\"\nORDER BY\n    \"time\""
    },
    {
     "rawSql": "SELECT\n    DATE_TRUNC('month', TO_DATE(CONCAT(t.year, '-', t.month, '-01'), 'YYYY-MM-DD')) AS \"time\",\n    SUM(e.negative_opinion) AS \"Negative sentiments\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\nWHERE\n    e.country_id = $country\n    AND e.energy_type_id = $energy\n    AND t.year = $year\nGROUP BY\n    \"time\"\nORDER BY\n    \"time\""
    },
    {
     "rawSql": "SELECT\n    DATE_TRUNC('month', TO_DATE(CONCAT(t.year, '-', t.month, '-01'), 'YYYY-MM-DD')) AS \"time\",\n    SUM(e.neutral_opinion) AS \"Neutral sentiments\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\nWHERE\n    e.country_id = $country\n    AND e.energy_type_id = $energy\n    AND t.year = $year\nGROUP BY\n    \"time\"\nORDER BY\n    \"time\""
    }
   ]
  },
  {
   "title": "Evolution of emission linked to the energy production : ${country}, ${energy}, year ${year}",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 14, "x": 4, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n    DATE_TRUNC('month', TO_DATE(CONCAT(t.year, '-', t.month, '-01'), 'YYYY-MM-DD')) AS \"time\",\n    SUM(e.energy_emission) AS \"Emission in Mt\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\nWHERE\n    e.country_id = $country\n    AND e.energy_type_id = $energy\n    AND t.year = $year\nGROUP BY\n    \"time\"\nORDER BY\n    \"time\""
    }
   ]
  }
 ]
}