{
 "title": "Energy Dashboard overview",
 "time": { "from": "2015-12-31T12:00:00.000Z", "to": "2025-01-01T12:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "energy",
    "query": "SELECT DISTINCT type_name AS __text, energy_type_id AS __value FROM Energy_Type_Dim"
   },
   {
    "name": "country",
    "query": "SELECT DISTINCT country_name AS __text, country_id AS __value FROM Country_Dim"
   }
  ]
 },
 "panels": [
  {
   "title": "Evolution of energy production in ${country}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    TO_DATE(t.year || '-' || LPAD(t.month::TEXT, 2, '0'), 'YYYY-MM') AS \"time\",\n    SUM(e.energy_production) AS \"Wind\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\n    JOIN Energy_Type_Dim ed ON e.energy_type_id = ed.energy_type_id\nWHERE\n    ed.type_name = 'Wind'\n    AND e.country_id = $country \nGROUP BY\n    t.year, t.month\nORDER BY\n    t.year, t.month"
    },
    {
     "rawSql": "SELECT\n    TO_DATE(t.year || '-' || LPAD(t.month::TEXT, 2, '0'), 'YYYY-MM') AS \"time\",\n    SUM(e.energy_production) AS \"Solar\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\n    JOIN Energy_Type_Dim ed ON e.energy_type_id = ed.energy_type_id\nWHERE\n    ed.type_name = 'Solar'\n    AND e.country_id = $country \nGROUP BY\n    t.year, t.month\nORDER BY\n    t.year, t.month"
    },
    {
     "rawSql": "SELECT\n    TO_DATE(t.year || '-' || LPAD(t.month::TEXT, 2, '0'), 'YYYY-MM') AS \"time\",\n    SUM(e.energy_production) AS \"Nuclear\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\n    JOIN Energy_Type_Dim ed ON e.energy_type_id = ed.energy_type_id\nWHERE\n    ed.type_name = 'Nuclear'\n    AND e.country_id = $country \nGROUP BY\n    t.year, t.month\nORDER BY\n    t.year, t.month"
    },
    {
     "rawSql": "SELECT\n    TO_DATE(t.year || '-' || LPAD(t.month::TEXT, 2, '0'), 'YYYY-MM') AS \"time\",\n    SUM(e.energy_production) AS \"Hydraulic\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\n    JOIN Energy_Type_Dim ed ON e.energy_type_id = ed.energy_type_id\nWHERE\n    ed.type_name = 'Hydraulic'\n    AND e.country_id = $country \nGROUP BY\n    t.year, t.month\nORDER BY\n    t.year, t.month"
    },
    {
     "rawSql": "SELECT\n    TO_DATE(t.year || '-' || LPAD(t.month::TEXT, 2, '0'), 'YYYY-MM') AS \"time\",\n    SUM(e.energy_production) AS \"Fossile\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\n    JOIN Energy_Type_Dim ed ON e.energy_type_id = ed.energy_type_id\nWHERE\n    ed.type_name = 'Fossile'\n    AND e.country_id = $country \nGROUP BY\n    t.year, t.month\nORDER BY\n    t.year, t.month"
    }
   ]
  },
  {
   "title": "Evolution of CO2 emissions linked to electricity production in ${country}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    TO_DATE(t.year || '-' || LPAD(t.month::TEXT, 2, '0'), 'YYYY-MM') AS \"time\",\n    SUM(e.energy_emission) AS \"Wind\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\n    JOIN Energy_Type_Dim ed ON e.energy_type_id = ed.energy_type_id\nWHERE\n    ed.type_name = 'Wind'\n    AND e.country_id = $country \nGROUP BY\n    t.year, t.month\nORDER BY\n    t.year, t.month"
    },
    {
     "rawSql": "SELECT\n    TO_DATE(t.year || '-' || LPAD(t.month::TEXT, 2, '0'), 'YYYY-MM') AS \"time\",\n    SUM(e.energy_emission) AS \"Solar\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\n    JOIN Energy_Type_Dim ed ON e.energy_type_id = ed.energy_type_id\nWHERE\n    ed.type_name = 'Solar'\n    AND e.country_id = $country \nGROUP BY\n    t.year, t.month\nORDER BY\n    t.year, t.month"
    },
    {
     "rawSql": "SELECT\n    TO_DATE(t.year || '-' || LPAD(t.month::TEXT, 2, '0'), 'YYYY-MM') AS \"time\",\n    SUM(e.energy_emission) AS \"Nuclear\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\n    JOIN Energy_Type_Dim ed ON e.energy_type_id = ed.energy_type_id\nWHERE\n    ed.type_name = 'Nuclear'\n    AND e.country_id = $country \nGROUP BY\n    t.year, t.month\nORDER BY\n    t.year, t.month"
    },
    {
     "rawSql": "SELECT\n    TO_DATE(t.year || '-' || LPAD(t.month::TEXT, 2, '0'), 'YYYY-MM') AS \"time\",\n    SUM(e.energy_emission) AS \"Hydraulic\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\n    JOIN Energy_Type_Dim ed ON e.energy_type_id = ed.energy_type_id\nWHERE\n    ed.type_name = 'Hydraulic'\n    AND e.country_id = $country \nGROUP BY\n    t.year, t.month\nORDER BY\n    t.year, t.month"
    },
    {
     "rawSql": "SELECT\n    TO_DATE(t.year || '-' || LPAD(t.month::TEXT, 2, '0'), 'YYYY-MM') AS \"time\",\n    SUM(e.energy_emission) AS \"Fossile\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\n    JOIN Energy_Type_Dim ed ON e.energy_type_id = ed.energy_type_id\nWHERE\n    ed.type_name = 'Fossile'\n    AND e.country_id = $country \nGROUP BY\n    t.year, t.month\nORDER BY\n    t.year, t.month"
    }
   ]
  },
  {
   "title": "Evolution of the public opinion in ${country} about ${energy}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n    TO_DATE(t.year || '-' || LPAD(t.month::TEXT, 2, '0'), 'YYYY-MM') AS \"time\",\n    SUM(e.positive_opinion) AS \"Positive sentiment\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\nWHERE\n    e.country_id = $country \n    AND e.energy_type_id = $energy \nGROUP BY\n    t.year, t.month\nORDER BY\n    t.year, t.month"
    },
    {
     "rawSql": "SELECT\n    TO_DATE(t.year || '-' || LPAD(t.month::TEXT, 2, '0'), 'YYYY-MM') AS \"time\",\n    SUM(e.neutral_opinion) AS \"Neutral sentiment\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\nWHERE\n    e.country_id = $country \n    AND e.energy_type_id = $energy \nGROUP BY\n    t.year, t.month\nORDER BY\n    t.year, t.month"
    },
    {
     "rawSql": "SELECT\n    TO_DATE(t.year || '-' || LPAD(t.month::TEXT, 2, '0'), 'YYYY-MM') AS \"time\",\n    SUM(e.negative_opinion) AS \"Negative sentiment\"\nFROM\n    Energy_Impact e\n    JOIN Time_Dim t ON e.time_id = t.time_id\nWHERE\n    e.country_id = $country \n    AND e.energy_type_id = $energy \nGROUP BY\n    t.year, t.month\nORDER BY\n    t.year, t.month"
    }
   ]
  }
 ]
}